print("Hello! This is a madlib. You will be asked to give word types, and then when all of the blanks are filled, then you will read the entire madlib. Have fun!")
print()
country = input("Alright! So first we need a country! " )
animal1 = input("Cool! Now we need a animal! ")
adjective1 = input("Alright. Next we need an adjective. slimy, anyone? ")
adjective2 = input("Now we need a different adjective. Im looking at you, Henry! ")
number = input("Now we need a number. these are getting hilarious! ")
animal2 = input("Now we need another animal, maybe like a kangaroo. ")
verb = input("We need a verb next. Like run for example. ")
sport = input("For the semifinal word, we need a sport! ")
day_of_the_week = input("Finally, we need a day of the week. ")
print()
print()
print(f"We have discovered a new animal called the Austrian Homunculus! It was found in {country} at 12:48.")
print()
print(f" It has the qualities similar to that of an {animal1}, including being {adjective1}, as well as being {adjective2} ")
print()
print(f"They seem to live to the age of {number}, almost like a {animal2}. ")
print()
print(f"They like to {verb}, as well as play {sport} for sport")
print()
print(f"That's all for now! See you on {day_of_the_week}! ")