print("Hello! This is a madlib. You will be asked to give word types, and then when all of the blanks are filled, then you will read the entire madlib. Have fun!")
print()
country = input("Alright! So first we need a country! " )
animal1 = input("Cool! Now we need a animal! ")
adjective1 = input("Alright. Next we need an adjective. slimy, anyone? ")
adjective2 = input("Now we need a different adjective. Im looking at you, Henry! ")
number = input("Now we need a number. these are getting hilarious! ")
animal2 = input("Now we need another animal, maybe like a kangaroo. ")
print(country)
print(animal1)
print(adjective1)
print(adjective2)
print(number)
print(animal2)
